
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int VAL = 51;
  public static final int DOSPUNTOS = 21;
  public static final int ABREBLOQUE = 35;
  public static final int DE = 32;
  public static final int CONST = 53;
  public static final int POR = 4;
  public static final int PUNTOYCOMA = 29;
  public static final int TIPO_REAL = 45;
  public static final int IMPRIMIR = 37;
  public static final int PCIERRE = 23;
  public static final int ENTERO = 56;
  public static final int SI = 39;
  public static final int PRINC = 30;
  public static final int CIERTO = 61;
  public static final int ENTONCES = 33;
  public static final int REF = 52;
  public static final int NOT = 15;
  public static final int MENORIGUAL = 11;
  public static final int AND = 13;
  public static final int IGUAL = 7;
  public static final int CARACTER = 59;
  public static final int SINO = 40;
  public static final int OR = 14;
  public static final int TIPO_CARACTER = 46;
  public static final int MIENTRAS = 41;
  public static final int CONTPUNT = 17;
  public static final int DIV = 5;
  public static final int CC = 25;
  public static final int THIS = 54;
  public static final int CA = 24;
  public static final int MAYORIGUAL = 12;
  public static final int DIST = 8;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 27;
  public static final int LLAVEAPERTURA = 26;
  public static final int SIZE = 50;
  public static final int CLASE = 49;
  public static final int TIPO_ENTERO = 44;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int CADENA = 60;
  public static final int MENOS = 3;
  public static final int NULL = 63;
  public static final int MENOR = 9;
  public static final int MOD = 6;
  public static final int DIRECCION = 18;
  public static final int CIERRABLOQUE = 36;
  public static final int ASIGNACION = 16;
  public static final int REAL = 57;
  public static final int NUEVO = 42;
  public static final int MAYOR = 10;
  public static final int PAP = 22;
  public static final int FLECHA = 20;
  public static final int VACIO = 48;
  public static final int FUNC = 31;
  public static final int IDEN = 55;
  public static final int ACCESO = 19;
  public static final int FALSO = 62;
  public static final int LEER = 38;
  public static final int HACER = 34;
  public static final int BOOLEANO = 58;
  public static final int TIPO_BOOLEANO = 43;
  public static final int TIPO_CADENA = 47;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
      "EOF",
      "error",
      "MAS",
      "MENOS",
      "POR",
      "DIV",
      "MOD",
      "IGUAL",
      "DIST",
      "MENOR",
      "MAYOR",
      "MENORIGUAL",
      "MAYORIGUAL",
      "AND",
      "OR",
      "NOT",
      "ASIGNACION",
      "CONTPUNT",
      "DIRECCION",
      "ACCESO",
      "FLECHA",
      "DOSPUNTOS",
      "PAP",
      "PCIERRE",
      "CA",
      "CC",
      "LLAVEAPERTURA",
      "LLAVECIERRE",
      "COMA",
      "PUNTOYCOMA",
      "PRINC",
      "FUNC",
      "DE",
      "ENTONCES",
      "HACER",
      "ABREBLOQUE",
      "CIERRABLOQUE",
      "IMPRIMIR",
      "LEER",
      "SI",
      "SINO",
      "MIENTRAS",
      "NUEVO",
      "TIPO_BOOLEANO",
      "TIPO_ENTERO",
      "TIPO_REAL",
      "TIPO_CARACTER",
      "TIPO_CADENA",
      "VACIO",
      "CLASE",
      "SIZE",
      "VAL",
      "REF",
      "CONST",
      "THIS",
      "IDEN",
      "ENTERO",
      "REAL",
      "BOOLEANO",
      "CARACTER",
      "CADENA",
      "CIERTO",
      "FALSO",
      "NULL"
  };
}
